name: Build and Deploy CTFd instance

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set repo name lowercase
      id: repo
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ github.repository }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.psuccso.org
        username: robot$ctfd
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Tag Names
      run: |
        repo="${{ steps.repo.outputs.lowercase }}"  # will just be 'ctfd-sso'
        short_sha=$(git rev-parse --short HEAD)
        echo "TAG_LATEST=$repo:latest" >> $GITHUB_ENV
        echo "TAG_COMMIT=$repo:$short_sha" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: |
          harbor.psuccso.org/${{ env.TAG_LATEST }}
          harbor.psuccso.org/${{ env.TAG_COMMIT }}
        cache-from: type=registry,ref=harbor.psuccso.org/${{ env.TAG_LATEST }}
        cache-to: type=inline

  deploy-rancher:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Redeploy Rancher
      run: |
        url='https://rancher.psuccso.org'
        cluster=local
        token=${{ secrets.RANCHER_TOKEN }}
        app="${{ github.event.repository.name }}"
        namespace="${{ github.event.repository.name }}"

        redeploy() {
            pod_upgrade_body=$(curl -s -u "$token" \
            -k $url/k8s/clusters/$cluster/v1/apps.deployments/$namespace/$app \
            -X GET \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            | sed "s/\"cattle\.io\/timestamp\":\"[0-9T:Z-]*\"/\"cattle\.io\/timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"/g")

            curl -u "$token" \
            -k -s $url/k8s/clusters/$cluster/v1/apps.deployments/$namespace/$app \
            -X PUT \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            --data-binary "$pod_upgrade_body"
        }

        redeploy
